#############################################################################
# Makefile for building: modbusCom
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  modbusCom.pro
# Template: app
# Command: /opt/fslc-framebuffer/2.3/icore/sysroots/x86_64-fslcsdk-linux/usr/bin/qt5/qmake -o Makefile modbusCom.pro -spec linux-oe-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-fslc-linux-gnueabi-gcc  -march=armv7-a -mthumb -mfpu=neon  -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi
CXX           = arm-fslc-linux-gnueabi-g++  -march=armv7-a -mthumb -mfpu=neon  -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi
DEFINES       = 
CFLAGS        = -pipe  -O2 -pipe --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi -O2 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi -O2 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Ilibmodbus -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++
QMAKE         = /opt/fslc-framebuffer/2.3/icore/sysroots/x86_64-fslcsdk-linux/usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = modbusCom1.0.0
DISTDIR = /home/user/ECOFILL/modbusCom/.tmp/modbusCom1.0.0
LINK          = arm-fslc-linux-gnueabi-g++  -march=armv7-a -mthumb -mfpu=neon  -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi
LFLAGS        = -Wl,-O1 --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi -Wl,-O1
LIBS          = $(SUBLIBS) -lrt 
AR            = arm-fslc-linux-gnueabi-ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.c \
		libmodbus/modbus-tcp.c \
		libmodbus/modbus-rtu.c \
		libmodbus/modbus-data.c \
		libmodbus/modbus.c 
OBJECTS       = main.o \
		modbus-tcp.o \
		modbus-rtu.o \
		modbus-data.o \
		modbus.o
DIST          = /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qdevice.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/device_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf \
		modbusCom.pro libmodbus/modbus-version.h \
		libmodbus/modbus-tcp-private.h \
		libmodbus/modbus-tcp.h \
		libmodbus/modbus-rtu-private.h \
		libmodbus/modbus-rtu.h \
		libmodbus/modbus-private.h \
		libmodbus/modbus.h \
		libmodbus/config.h main.c \
		libmodbus/modbus-tcp.c \
		libmodbus/modbus-rtu.c \
		libmodbus/modbus-data.c \
		libmodbus/modbus.c
QMAKE_TARGET  = modbusCom
DESTDIR       = 
TARGET        = modbusCom


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: modbusCom.pro /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qdevice.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/device_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf \
		modbusCom.pro
	$(QMAKE) -o Makefile modbusCom.pro -spec linux-oe-g++
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qdevice.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/device_config.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/toolchain.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf:
modbusCom.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile modbusCom.pro -spec linux-oe-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.c libmodbus/modbus.h \
		libmodbus/modbus-version.h \
		libmodbus/modbus-tcp.h \
		libmodbus/modbus-rtu.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o main.o main.c

modbus-tcp.o: libmodbus/modbus-tcp.c libmodbus/modbus-private.h \
		libmodbus/config.h \
		libmodbus/modbus.h \
		libmodbus/modbus-version.h \
		libmodbus/modbus-tcp.h \
		libmodbus/modbus-rtu.h \
		libmodbus/modbus-tcp-private.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus-tcp.o libmodbus/modbus-tcp.c

modbus-rtu.o: libmodbus/modbus-rtu.c libmodbus/modbus-private.h \
		libmodbus/config.h \
		libmodbus/modbus.h \
		libmodbus/modbus-version.h \
		libmodbus/modbus-tcp.h \
		libmodbus/modbus-rtu.h \
		libmodbus/modbus-rtu-private.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus-rtu.o libmodbus/modbus-rtu.c

modbus-data.o: libmodbus/modbus-data.c libmodbus/modbus.h \
		libmodbus/modbus-version.h \
		libmodbus/modbus-tcp.h \
		libmodbus/modbus-rtu.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus-data.o libmodbus/modbus-data.c

modbus.o: libmodbus/modbus.c libmodbus/config.h \
		libmodbus/modbus.h \
		libmodbus/modbus-version.h \
		libmodbus/modbus-tcp.h \
		libmodbus/modbus-rtu.h \
		libmodbus/modbus-private.h
	$(CC) -c $(CFLAGS) $(INCPATH) -o modbus.o libmodbus/modbus.c

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

